


package com.example.springbootswagger2.copybook.transaction.bind;

import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.ICobolStringBinding;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.example.springbootswagger2.copybook.transaction.So1Record;
import com.example.springbootswagger2.copybook.transaction.ObjectFactory;

/**
 * LegStar Binding for Complex element :
 *   So1Record.
 * 
 * This class was generated by LegStar Binding generator.
 */
public class So1RecordBinding 
             extends CComplexBinding {

    /** Value object to which this cobol complex element is bound. */
    private So1Record mValueObject;
  
    /** Indicates that the associated Value object just came from the constructor
     * and doesn't need to be recreated. */
    private boolean mUnusedValueObject = false;
    
    /** Maximum host bytes size for this complex object. */
    private static final int BYTE_LENGTH = 30;
    
    /** Child bound to value object property So1Name(String). */
    public ICobolStringBinding _so1Name;
    /** Child bound to value object property So1Class(String). */
    public ICobolStringBinding _so1Class;
    /** Child bound to value object property So1Country(String). */
    public ICobolStringBinding _so1Country;
            
    /** Logger. */
    private final Log _log = LogFactory.getLog(getClass());

    /** Binding factory. */
    private static final ICobolBindingFactory BF
        = CobolBindingFactory.getBindingFactory();
 
    /** Static reference to Value object factory to be used as default. */
    private static final ObjectFactory JF = new ObjectFactory();
    
    /** Current Value object factory (Defaults to the static one but can be
     *  changed). */
    private ObjectFactory mValueObjectFactory = JF;
    
    /**
     * Constructor for a root Complex element without a bound Value object.
     */
    public So1RecordBinding() {
        this(null);
    }

    /**
     * Constructor for a root Complex element with a bound Value object.
     * 
     * @param valueObject the concrete Value object instance bound to this
     *        complex element
     */
    public So1RecordBinding(
            final So1Record valueObject) {
        this("", "", null, valueObject);
    }

    /**
    * Constructor for a Complex element as a child of another element and
    * an associated Value object.
    * 
    * @param bindingName the identifier for this binding
    * @param fieldName field name in parent Value object
    * @param valueObject the concrete Value object instance bound to this
    *        complex element
    * @param parentBinding a reference to the parent binding
    */
    public So1RecordBinding(
            final String bindingName,
            final String fieldName,
            final ICobolComplexBinding parentBinding,
            final So1Record valueObject) {
        
        super(bindingName, fieldName, So1Record.class, null, parentBinding);
        mValueObject = valueObject;
        if (mValueObject != null) {
            mUnusedValueObject = true;
        }
        initChildren();
        setByteLength(BYTE_LENGTH);
    }

    /** Creates a binding property for each child. */
    private void initChildren() {
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing started");
        }
        /* Create binding children instances */

        _so1Name = BF.createStringBinding("So1Name",
               "So1Name", String.class, this);
        _so1Name.setCobolName("SO1-NAME");
        _so1Name.setByteLength(10);
        _so1Class = BF.createStringBinding("So1Class",
               "So1Class", String.class, this);
        _so1Class.setCobolName("SO1-CLASS");
        _so1Class.setByteLength(10);
        _so1Country = BF.createStringBinding("So1Country",
               "So1Country", String.class, this);
        _so1Country.setCobolName("SO1-COUNTRY");
        _so1Country.setByteLength(10);

        /* Add children to children list */
        getChildrenList().add(_so1Name);
        getChildrenList().add(_so1Class);
        getChildrenList().add(_so1Country);
 
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing successful");
        }
    }
    
    /** {@inheritDoc} */
    public void createValueObject() throws HostException {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
        if (mUnusedValueObject && mValueObject != null) {
            mUnusedValueObject = false;
            return;
        }
        mValueObject = mValueObjectFactory.createSo1Record();
    }

    /** {@inheritDoc} */
    public void setChildrenValues() throws HostException {

         /* Make sure there is an associated Value object*/
        if (mValueObject == null) {
            createValueObject();
        }
        /* Get Value object property _so1Name */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_so1Name"
                    + " value=" + mValueObject.getSo1Name());
        }
        _so1Name.setObjectValue(mValueObject.getSo1Name());
        /* Get Value object property _so1Class */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_so1Class"
                    + " value=" + mValueObject.getSo1Class());
        }
        _so1Class.setObjectValue(mValueObject.getSo1Class());
        /* Get Value object property _so1Country */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_so1Country"
                    + " value=" + mValueObject.getSo1Country());
        }
        _so1Country.setObjectValue(mValueObject.getSo1Country());
     }

    /** {@inheritDoc} */
    public void setPropertyValue(final int index) throws HostException {
 
        ICobolBinding child = getChildrenList().get(index);
        
       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
        if (!child.isBound()) {
            return;
        }
        
        /* Set the Value object property value from binding object */
        Object bindingValue = null;
        switch (index) {
        case 0:
            bindingValue = child.getObjectValue(String.class);
            mValueObject.setSo1Name((String) bindingValue);
            break;
        case 1:
            bindingValue = child.getObjectValue(String.class);
            mValueObject.setSo1Class((String) bindingValue);
            break;
        case 2:
            bindingValue = child.getObjectValue(String.class);
            mValueObject.setSo1Country((String) bindingValue);
            break;
         default:
            break;
        }
        if (_log.isDebugEnabled()) {
            _log.debug("Setting value of Value object property "
                    + child.getJaxbName()
                    + " value=" + bindingValue);
        }
    }

    /** {@inheritDoc} */
    public Object getObjectValue(
            final Class < ? > type) throws HostException {
        if (type.equals(So1Record.class)) {
            return mValueObject;
        } else {
            throw new HostException("Attempt to get binding " + getBindingName()
                    + " as an incompatible type " + type);
        }
    }

    /** {@inheritDoc} */
    public void setObjectValue(
            final Object bindingValue) throws HostException {
        if (bindingValue == null) {
            mValueObject = null;
            return;
        }
        if (bindingValue.getClass().equals(So1Record.class)) {
            mValueObject = (So1Record) bindingValue;
        } else {
            throw new HostException("Attempt to set binding " + getBindingName()
                    + " from an incompatible value " + bindingValue);
        }
    }

    /**
     * @return the java object factory for objects creation
     */
    public ObjectFactory getObjectFactory() {
        return mValueObjectFactory;
    }

    /**
     * @param valueObjectFactory the java object factory for objects creation 
     */
    public void setObjectFactory(final Object valueObjectFactory) {
        mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

    /** {@inheritDoc} */
    public boolean isSet() {
        return (mValueObject != null);
    }

    /**
     * @return the bound Value object
     */
    public So1Record getSo1Record() {
        return mValueObject;
    }
    
    /**
     * The COBOL complex element maximum length in bytes.
     * 
     * @return COBOL complex element maximum length in bytes
     */
    public int getByteLength() {
        return BYTE_LENGTH;
    }
}

